### PR TITLE
Update scripts/core.sh

### PR DESCRIPTION
**Pull request by psyhtest**
See https://github.com/pencil-language/pencil-benchmark/issues/2

### CODE REVIEW

**Comment by psyhtest** [comment]
Sorry, I only intended to include `86b8920`. Not sure if I can separate it now from the others changes: `eff705d` for [issue 1](https://github.com/pencil-language/pencil-benchmark/issues/1) and `f5a8d47` for further `pencilcc`-related changes.

**Comment by rbaghdadi** [comment]
All the changes are good for me except the changes on scripts/scripts_config.conf, all the changes to that files are not Ok for me.  I guess you committed it by error.

**Comment by rbaghdadi** [comment]
Can you remove all the changes on scripts/scripts_config.conf and do a second pull request ?

**Comment by rbaghdadi** [comment]
On 13/10/2015 11:40, Anton Lokhmotov wrote:

> Sorry, I only intended to include `86b8920`. Not sure if I can separate it now from the others changes: `eff705d` for [issue 1](https://github.com/pencil-language/pencil-benchmark/issues/1) and `f5a8d47` for further `pencilcc`-related changes.

I'm not very familiar with github, but you can cancel maybe your pull 
request and do a second pull request that inlcudes only the correct commits.

## 

Riyadh

**Comment by psyhtest** [comment]
I believe I have now only left changes for `86b8920` and `f5a8d47`. 

`eff705d` is still an example solution for [issue 1](#1) (as soon as it works).

**Comment by rbaghdadi** [comment]
No, it seems you remove the wrong one.  3b2c563 is the problematic commit and it is still there (it is the second in the list of your commits).

**Comment by psyhtest** [comment]
Sorry, it's the merge that ruined my plan. I'll close this pull request and try again with the changes suggested by Michael.

**Pull request closed without merging**
