### PR TITLE
Compile resize with pencilcc v0.4

### PR DESCRIPTION
**Pull request by psyhtest**
Update the `resize` benchmark in order to be able to compile it with `pencilcc` v0.4.

### CODE REVIEW

**Comment by Meinersbur** [comment]
@rbaghdadi 
The naming pattern for such builtins is still unsolved. Specifically, for clamp the generator would use the name "iclampi", but according to the specification it should be "clamp". The naming pattern of the specification also doesn't work universally because it clashes with other definitions (e.g. "min", "max")

Before this isn't resolved, I wouldn't re-add such defintions to the headers.

**Comment by rbaghdadi** [comment]
@Meinersbur 
Ok I see.  Then the pull request is fine for me.  Michale, do you want to take care of merging this ?

**Comment by Meinersbur** [comment]
Because this breaks when compiling with pencil-driver-0.3.x, shouldn't we make a branch for the ongoing conversion to pencilcc-0.4?

**Comment by psyhtest** [comment]
It's probably a good idea but since nobody uses the benchmarks at the moment, we could probably skip creating a branch. What do you think?

**Comment by Meinersbur** [comment]
That's fine with me. Less trouble managing branches.

**Comment by psyhtest** [comment]
Blast! I accidentally added stuff from my fork I didn't intend to. Do you know of any way of removing it?

**Comment by Meinersbur** [comment]
git reset --hard HEAD^

**Comment by psyhtest** [comment]
Thanks Michael! Can you please merge this pull request before I break it again? I promise I'm going to use branches for pull requests from now on.

**Pull request merged**
